/*
 * This source file was generated by the Gradle 'init' task
 */
package mg.dirk.vote_system;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        new AppWindow();
    }
}
